language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"

sudo: required

stages:
  - lint

services:
  - mysql

env:
  matrix:
    - SHOPWARE_VERSION="5.3"
    - SHOPWARE_VERSION="5.4"
    - SHOPWARE_VERSION="5.5"
  global:
    - PLUGIN_NAME=FinSearchUnified
    - SHOPWARE_DIRECTORY=${HOME}/shopware
    - PLUGIN_DIRECTORY=${SHOPWARE_DIRECTORY}/custom/plugins

cache:
  directories:
    - ${HOME}/.composer/cache/files

before_install:
  - sudo apt-get install ant

install:
  - cd ${PLUGIN_NAME}
  - composer install

before_script:
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
  - git clone https://github.com/shopware/shopware.git ${SHOPWARE_DIRECTORY} --branch ${SHOPWARE_VERSION}
  - ant -f ${SHOPWARE_DIRECTORY}/build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
  - mv ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME} ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}
  - php ${SHOPWARE_DIRECTORY}/bin/console sw:plugin:refresh
  - php ${SHOPWARE_DIRECTORY}/bin/console sw:plugin:install ${PLUGIN_NAME}
  - php ${SHOPWARE_DIRECTORY}/bin/console sw:plugin:activate ${PLUGIN_NAME}
  - php ${SHOPWARE_DIRECTORY}/bin/console sw:cache:clear
  - ${SHOPWARE_DIRECTORY}/var/cache/clear_cache.sh
  - cd ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}

script:
  - composer test

jobs:
  include:
    - stage: lint
      before_script: skip
      script: composer lint
    - stage: Shopware 5.6
      php: 7.3
      env:
        - SHOPWARE_VERSION="5.6"
