language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"

sudo: required

services:
  - mysql

env:
  matrix:
    - SHOPWARE_VERSION="5.3"
    - SHOPWARE_VERSION="5.4"
    - SHOPWARE_VERSION="5.5"
  global:
    - PLUGIN_NAME=FinSearchUnified
    - SHOPWARE_DIRECTORY=${HOME}/shopware
    - PLUGIN_DIRECTORY=${SHOPWARE_DIRECTORY}/custom/plugins
  - TEST_SUITE="composer lint"
  - TEST_SUITE="composer test"

cache:
  directories:
    - ${HOME}/.composer/cache/files

install:
  - cd ${PLUGIN_NAME}
  - composer install

before_script:
  - cd ..
  - ./travis/before-script.sh
  - cd ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}

script: $TEST_SUITE
