# Shopware 5.2 - 5.5 run on PHP versions 5.6, 7.0 and 7.1.
name: PHPUnit (SW 5.2 - 5.5)

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.6', '7.0', '7.1']
        shopware-versions: ['5.2', 'v5.2.0', '5.3', 'v5.3.0', '5.4', '5.5']

    name: Shopware ${{ matrix.shopware-versions }} Test (PHP ${{ matrix.php-versions }})
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: shopware
          mysql root password: shopware

      - uses: actions/checkout@v2
        with:
          path: plugin-shopware-5

      - name: Setup PHP with Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          # PHP bug https://bugs.php.net/bug.php?id=66773 imports classes with wrong namespace information,
          # which may result in classes being imported from a wrong namespace, causing conflicts.
          # This bug has been fixed with PHP 7.
          ini-values: opcache.enable_cli=1,opcache.file_cache=/tmp/opcache
          extensions: mbstring, dom, gd, pdo_mysql, zip
          coverage: xdebug
          tools: composer:v2

      - name: Validate dependencies
        run: |
          cd plugin-shopware-5/FinSearchUnified
          composer validate

      - name: Clone Shopware repository
        uses: actions/checkout@v2
        with:
          repository: shopware/shopware
          ref: ${{ matrix.shopware-versions }}
          path: shopware
          fetch-depth: 0

      - name: Install Shopware
        run: |
          cd shopware
          ant -f build/build.xml -Dapp.host=localhost -Ddb.user=root -Ddb.password=shopware -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit

      - name: Install Plugin dependencies
        run: |
          cd plugin-shopware-5/FinSearchUnified
          composer install --no-interaction

      - name: Install Plugin
        run: |
          mv plugin-shopware-5/FinSearchUnified shopware/custom/plugins
          cd shopware
          php bin/console sw:plugin:refresh
          php bin/console sw:plugin:install FinSearchUnified
          php bin/console sw:plugin:activate FinSearchUnified
          php bin/console sw:cache:clear

      # Update PHPUnit to a more recent version, as older versions didn't have proper namespace support.
      - name: Update PhpUnit version
        run: |
          cd shopware
          composer update "phpunit/phpunit:5.7.27" --with-dependencies
          composer dump-autoload -o # See https://issues.shopware.com/issues/SW-15496

      - name: Run test suite
        run: |
          cd shopware/custom/plugins/FinSearchUnified
          SHOPWARE_VERSION=${{ matrix.shopware-versions }} composer test
        # Shopware v5.2.0 did not support >= PHP 7, therefore we can not test these versions.
        if: ${{ !(( matrix.shopware-versions == 'v5.2.0' && matrix.php-versions == '7.0') || (matrix.shopware-versions == 'v5.2.0' && matrix.php-versions == '7.1')) }}
