# Shopware 5.7 run on PHP version 7.4
name: PHPUnit (SW 5.7)

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        php-versions: ['7.4']
        shopware-versions: ['5.7']
    runs-on: ubuntu-latest
    env:
      DB_USER: root
      DB_PASSWORD: shopware
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: shopware
      SW_HOST: localhost
      SW_BASE_PATH: ''

    name: Shopware ${{ matrix.shopware-versions }} Test (PHP ${{ matrix.php-versions }})
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: shopware
          mysql root password: shopware

      - uses: actions/checkout@v2
        with:
          path: plugin-shopware-5

      - name: Setup PHP with Composer 2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, gd, pdo_mysql, zip
          coverage: xdebug
          tools: composer:v2

      - name: Validate dependencies
        run: |
          cd plugin-shopware-5/FinSearchUnified
          composer validate

      - name: Clone Shopware repository
        uses: actions/checkout@v2
        with:
          repository: shopware/shopware
          ref: ${{ matrix.shopware-versions }}
          path: shopware

      - name: Install Shopware
        run: |
          cd shopware
          make init

      - name: Install Plugin dependencies
        run: |
          cd plugin-shopware-5/FinSearchUnified
          composer install --no-interaction

      - name: Install Plugin
        run: |
          mv plugin-shopware-5/FinSearchUnified shopware/custom/plugins
          cd shopware
          php bin/console sw:plugin:refresh
          php bin/console sw:plugin:install FinSearchUnified
          php bin/console sw:plugin:activate FinSearchUnified
          php bin/console sw:cache:clear

      - name: Run test suite
        run: |
          cd shopware/custom/plugins/FinSearchUnified
          composer test
